
_target_: lerobot.common.robot_devices.robots.mycobot.MyCobot
robot_type: mycobot

cameras:
  head:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 0
    fps: 30
    width: 640
    height: 480
